version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - cd website/editor
      - yarn
      - cd ../..
  build:
    commands:
      - cd website/editor
      - node src/loadVersions.js
      - npx parcel build -d ../../dist --no-autoinstall --public-url 'https://editor-prod.effector.dev' src/index.html
      - cd ../..
      - cp -a website/client/static/. dist/
      - cp -a website/media/. dist/
      - cp -a website/editor/robots.txt dist/
      - aws cloudfront create-invalidation --distribution-id $cloudfront_static --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: dist
  # secondary-artifacts:
  #   frontend-build:
  #     files:
  #       - '**/*'
  #     base-directory: `frontend/dist
  #     name: frontend-build
